# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import testenum_pb2 as testenum__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.empty_pb2 import *
from google.protobuf.wrappers_pb2 import *
from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ntest.proto\x12\x04test\x1a\x0etestenum.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x01\n\x04Test\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1c\n\x04\x65num\x18\x03 \x01(\x0e\x32\x0e.test.TestEnum\x12\x0f\n\x07is_okay\x18\x04 \x01(\x08\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1f\n\x07oneof_1\x18\x07 \x01(\x0b\x32\x0c.test.OneOf1H\x00\x12\x1f\n\x07oneof_2\x18\x08 \x01(\x0b\x32\x0c.test.OneOf2H\x00\x42\x0c\n\noneof_test\"=\n\x06OneOf1\x12\n\n\x02id\x18\x01 \x01(\x04\x12\'\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x15.test.RepeatedTestObj\"C\n\x06OneOf2\x12\n\n\x02id\x18\x01 \x01(\x04\x12-\n\rtest_entities\x18\x02 \x03(\x0b\x32\x16.test.RepeatedTestObj2\"\xe4\x01\n\x0fRepeatedTestObj\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08is_right\x18\x02 \x01(\x08\x12\x30\n\tobjective\x18\x04 \x01(\x0b\x32\x1b.test.RepeatedTestObj.TypeAH\x00\x12\x31\n\nsubjective\x18\x05 \x01(\x0b\x32\x1b.test.RepeatedTestObj.TypeBH\x00\x1a(\n\x05TypeA\x12\r\n\x05index\x18\x01 \x03(\r\x12\x10\n\x08response\x18\x02 \x03(\r\x1a\x17\n\x05TypeB\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\tB\x0b\n\ttype_spec\"\x1e\n\x10RepeatedTestObj2\x12\n\n\x02id\x18\x01 \x01(\tP\x01P\x02P\x03\x62\x06proto3')
  ,
  dependencies=[testenum__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,],
  public_dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='test.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.Test.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='test.Test.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum', full_name='test.Test.enum', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_okay', full_name='test.Test.is_okay', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='test.Test.created_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='test.Test.updated_at', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oneof_1', full_name='test.Test.oneof_1', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oneof_2', full_name='test.Test.oneof_2', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='oneof_test', full_name='test.Test.oneof_test',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=131,
  serialized_end=386,
)


_ONEOF1 = _descriptor.Descriptor(
  name='OneOf1',
  full_name='test.OneOf1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.OneOf1.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entities', full_name='test.OneOf1.entities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=449,
)


_ONEOF2 = _descriptor.Descriptor(
  name='OneOf2',
  full_name='test.OneOf2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.OneOf2.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_entities', full_name='test.OneOf2.test_entities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=518,
)


_REPEATEDTESTOBJ_TYPEA = _descriptor.Descriptor(
  name='TypeA',
  full_name='test.RepeatedTestObj.TypeA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='test.RepeatedTestObj.TypeA.index', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='test.RepeatedTestObj.TypeA.response', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=671,
  serialized_end=711,
)

_REPEATEDTESTOBJ_TYPEB = _descriptor.Descriptor(
  name='TypeB',
  full_name='test.RepeatedTestObj.TypeB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='test.RepeatedTestObj.TypeB.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=713,
  serialized_end=736,
)

_REPEATEDTESTOBJ = _descriptor.Descriptor(
  name='RepeatedTestObj',
  full_name='test.RepeatedTestObj',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.RepeatedTestObj.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_right', full_name='test.RepeatedTestObj.is_right', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objective', full_name='test.RepeatedTestObj.objective', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subjective', full_name='test.RepeatedTestObj.subjective', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REPEATEDTESTOBJ_TYPEA, _REPEATEDTESTOBJ_TYPEB, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='type_spec', full_name='test.RepeatedTestObj.type_spec',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=521,
  serialized_end=749,
)


_REPEATEDTESTOBJ2 = _descriptor.Descriptor(
  name='RepeatedTestObj2',
  full_name='test.RepeatedTestObj2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.RepeatedTestObj2.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=751,
  serialized_end=781,
)

_TEST.fields_by_name['enum'].enum_type = testenum__pb2._TESTENUM
_TEST.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TEST.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TEST.fields_by_name['oneof_1'].message_type = _ONEOF1
_TEST.fields_by_name['oneof_2'].message_type = _ONEOF2
_TEST.oneofs_by_name['oneof_test'].fields.append(
  _TEST.fields_by_name['oneof_1'])
_TEST.fields_by_name['oneof_1'].containing_oneof = _TEST.oneofs_by_name['oneof_test']
_TEST.oneofs_by_name['oneof_test'].fields.append(
  _TEST.fields_by_name['oneof_2'])
_TEST.fields_by_name['oneof_2'].containing_oneof = _TEST.oneofs_by_name['oneof_test']
_ONEOF1.fields_by_name['entities'].message_type = _REPEATEDTESTOBJ
_ONEOF2.fields_by_name['test_entities'].message_type = _REPEATEDTESTOBJ2
_REPEATEDTESTOBJ_TYPEA.containing_type = _REPEATEDTESTOBJ
_REPEATEDTESTOBJ_TYPEB.containing_type = _REPEATEDTESTOBJ
_REPEATEDTESTOBJ.fields_by_name['objective'].message_type = _REPEATEDTESTOBJ_TYPEA
_REPEATEDTESTOBJ.fields_by_name['subjective'].message_type = _REPEATEDTESTOBJ_TYPEB
_REPEATEDTESTOBJ.oneofs_by_name['type_spec'].fields.append(
  _REPEATEDTESTOBJ.fields_by_name['objective'])
_REPEATEDTESTOBJ.fields_by_name['objective'].containing_oneof = _REPEATEDTESTOBJ.oneofs_by_name['type_spec']
_REPEATEDTESTOBJ.oneofs_by_name['type_spec'].fields.append(
  _REPEATEDTESTOBJ.fields_by_name['subjective'])
_REPEATEDTESTOBJ.fields_by_name['subjective'].containing_oneof = _REPEATEDTESTOBJ.oneofs_by_name['type_spec']
DESCRIPTOR.message_types_by_name['Test'] = _TEST
DESCRIPTOR.message_types_by_name['OneOf1'] = _ONEOF1
DESCRIPTOR.message_types_by_name['OneOf2'] = _ONEOF2
DESCRIPTOR.message_types_by_name['RepeatedTestObj'] = _REPEATEDTESTOBJ
DESCRIPTOR.message_types_by_name['RepeatedTestObj2'] = _REPEATEDTESTOBJ2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), dict(
  DESCRIPTOR = _TEST,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.Test)
  ))
_sym_db.RegisterMessage(Test)

OneOf1 = _reflection.GeneratedProtocolMessageType('OneOf1', (_message.Message,), dict(
  DESCRIPTOR = _ONEOF1,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.OneOf1)
  ))
_sym_db.RegisterMessage(OneOf1)

OneOf2 = _reflection.GeneratedProtocolMessageType('OneOf2', (_message.Message,), dict(
  DESCRIPTOR = _ONEOF2,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.OneOf2)
  ))
_sym_db.RegisterMessage(OneOf2)

RepeatedTestObj = _reflection.GeneratedProtocolMessageType('RepeatedTestObj', (_message.Message,), dict(

  TypeA = _reflection.GeneratedProtocolMessageType('TypeA', (_message.Message,), dict(
    DESCRIPTOR = _REPEATEDTESTOBJ_TYPEA,
    __module__ = 'test_pb2'
    # @@protoc_insertion_point(class_scope:test.RepeatedTestObj.TypeA)
    ))
  ,

  TypeB = _reflection.GeneratedProtocolMessageType('TypeB', (_message.Message,), dict(
    DESCRIPTOR = _REPEATEDTESTOBJ_TYPEB,
    __module__ = 'test_pb2'
    # @@protoc_insertion_point(class_scope:test.RepeatedTestObj.TypeB)
    ))
  ,
  DESCRIPTOR = _REPEATEDTESTOBJ,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.RepeatedTestObj)
  ))
_sym_db.RegisterMessage(RepeatedTestObj)
_sym_db.RegisterMessage(RepeatedTestObj.TypeA)
_sym_db.RegisterMessage(RepeatedTestObj.TypeB)

RepeatedTestObj2 = _reflection.GeneratedProtocolMessageType('RepeatedTestObj2', (_message.Message,), dict(
  DESCRIPTOR = _REPEATEDTESTOBJ2,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:test.RepeatedTestObj2)
  ))
_sym_db.RegisterMessage(RepeatedTestObj2)


# @@protoc_insertion_point(module_scope)
